spring:
  application:
    name: frindsnet
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    url: jdbc:h2:~/db_frindsnet;DB_CLOSE_DELAY=1000;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.springframework: INFO
server:
  port: 8089